-- 노란색 열쇠 pk

CREATE TABLE employees (
	EMP_NO INT(11)
	,BIRTH_DATE DATE
	,FIRST_NAME VARCHAR(14)
	,LAST_NAME VARCHAR(16)
	,GENDER ENUM('M','F')
	,HIRE_DATE DATE
	,CONSTRAINT PK_TEST_EMP_NO PRIMARY KEY(EMP_NO)
);

CREATE TABLE SALARIES (
	EMP_NO INT(11)
	,SALARY INT(11)
	,FROM_DATE DATE
	,TO_DATE DATE
	,PRIMARY KEY(EMP_NO,FROM_DATE)
);

CREATE TABLE TITLES (
	EMP_NO INT(11)
	,TITLE VARCHAR(50)
	,FROM_DATE DATE
	,TO_DATE DATE
	,PRIMARY KEY(EMP_NO,TITLE, FROM_DATE)
);

ALTER TABLE salaries
ADD CONSTRAINT FK_TEST_EMP_NO
FOREIGN KEY (EMP_NO)
REFERENCES employees (EMP_NO);

ALTER TABLE titles
ADD CONSTRAINT FK_TEST_EMP_NO2
FOREIGN KEY (EMP_NO)
REFERENCES employees (EMP_NO);

CREATE INDEX emp_no ON salaries (EMP_NO);
CREATE INDEX emp_no ON titles (EMP_NO);

CREATE TABLE DEPT_EMP (
	EMP_NO INT(11)
	,DEPT_NO CHAR(4)
	,FROM_DATE DATE
	,TO_DATE DATE
	,PRIMARY KEY(EMP_NO,DEPT_NO)
);

CREATE TABLE DEPT_MANAGER (
	DEPT_NO CHAR(4)
	,EMP_NO INT(11)
	,FROM_DATE DATE
	,TO_DATE DATE
	,PRIMARY KEY(DEPT_NO,EMP_NO)
);

CREATE TABLE DEPARTMENTS (
	DEPT_NO CHAR(4)
	,DEPT_NAME VARCHAR(40)
	,CONSTRAINT PK_TEST_DEPT_NO PRIMARY KEY(DEPT_NO)
);

ALTER TABLE dept_emp
ADD FOREIGN KEY (DEPT_NO)
REFERENCES departments (DEPT_NO);

ALTER TABLE dept_emp
ADD FOREIGN KEY (EMP_NO)
REFERENCES employees (EMP_NO);

ALTER TABLE dept_manager
ADD FOREIGN KEY (DEPT_NO)
REFERENCES departments (DEPT_NO);

ALTER TABLE dept_manager
ADD FOREIGN KEY (EMP_NO)
REFERENCES employees (EMP_NO);

CREATE INDEX dept_name ON departments (DEPT_NAME);
CREATE INDEX emp_no ON dept_emp (emp_no);
CREATE INDEX dept_no ON dept_manager (dept_no);

-- PK: 주민등록번호와 같이 레코드를 식별해줄 수 있는 고유한 데이터
-- FK: 외래키, 참조키