-- 한글은 한 글자에 3 바이트
-- 영어, 숫자는 한 글자에 1 바이트

CREATE TABLE TEST_TBL (
	MEM_NO INT(5)
	,MEM_NAME VARCHAR(50) NOT NULL
	,MEM_AGE INT(3) NOT NULL
	,MEM_SEX ENUM('F','M')
	,MEM_SIGNIN_DATE DATETIME NOT NULL
	,MEM_SIGNOUT_DATE DATETIME
	,CONSTRAINT PK_EMPLOYEES_MEM_NO PRIMARY KEY(MEM_NO)
);

ALTER TABLE test_tbl ADD COLUMN ADDR1 VARCHAR(300);

SHOW FULL COLUMNS FROM test_tbl;

ALTER TABLE test_tbl DROP COLUMN ADDR1;

INSERT INTO TEST_TBL (
	MEM_NO
	,MEM_NAME
	,MEM_AGE
	,MEM_SEX
	,MEM_SIGNIN_DATE
	,MEM_SIGNOUT_DATE
)
VALUES (
	1
	,'이가원'
	,26
	,'F'
	,NOW()
	,NULL
);

SELECT *
FROM test_tbl;

DELETE FROM test_tbl WHERE MEM_NO = 1;

TRUNCATE TABLE test_tbl;

DROP TABLE test_tbl;